import os
import random
import sqlite3
import time
from contextlib import contextmanager

DB_PATH = os.environ.get("DB_PATH", os.path.join(os.path.dirname(__file__), "data", "r2hub.db"))
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_PG = DATABASE_URL.startswith(("postgresql://", "postgres://"))

_pg_pool = None


def _pg():
    global _pg_pool
    if _pg_pool is None:
        from psycopg_pool import ConnectionPool

        max_size = int(os.environ.get("PG_POOL_MAX", "25"))
        _pg_pool = ConnectionPool(DATABASE_URL, min_size=1, max_size=max_size, open=True,
                                  kwargs={"autocommit": False})
    return _pg_pool


class _Cursor:
    def __init__(self, rows):
        self._rows = rows

    def fetchone(self):
        return self._rows[0] if self._rows else None

    def fetchall(self):
        return self._rows


class _PgConn:
    def __init__(self, conn):
        self._c = conn

    def execute(self, sql, params=()):
        cur = self._c.execute(sql.replace("?", "%s"), tuple(params))
        if cur.description:
            cols = [d.name for d in cur.description]
            return _Cursor([dict(zip(cols, row)) for row in cur.fetchall()])
        return _Cursor([])

    def commit(self):
        pass


class _SqliteConn:
    RETRIES = int(os.environ.get("SQLITE_LOCK_RETRIES", "60"))

    def __init__(self, conn):
        self._c = conn

    def execute(self, sql, params=()):
        delay = 0.03
        last = None
        for attempt in range(self.RETRIES):
            try:
                return self._c.execute(sql, tuple(params))
            except sqlite3.OperationalError as e:
                msg = str(e).lower()
                if ("locked" in msg or "busy" in msg) and attempt < self.RETRIES - 1:
                    last = e
                    time.sleep(delay + random.random() * delay)
                    delay = min(delay * 1.7, 0.6)
                    continue
                raise
        raise last

    def commit(self):
        self._c.commit()


def _connect_sqlite() -> sqlite3.Connection:
    d = os.path.dirname(DB_PATH)
    if d:
        os.makedirs(d, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=15)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=15000")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


@contextmanager
def db():
    if IS_PG:
        with _pg().connection() as c:
            yield _PgConn(c)
    else:
        conn = _connect_sqlite()
        try:
            yield _SqliteConn(conn)
            conn.commit()
        finally:
            conn.close()


SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS buckets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    label TEXT UNIQUE NOT NULL,
    account_id TEXT NOT NULL DEFAULT '',
    access_key_id TEXT NOT NULL,
    secret_access_key TEXT NOT NULL,
    bucket TEXT NOT NULL,
    endpoint TEXT NOT NULL DEFAULT '',
    public_base_url TEXT NOT NULL DEFAULT '',
    path_style INTEGER NOT NULL DEFAULT 1,
    enabled INTEGER NOT NULL DEFAULT 1,
    failed_count INTEGER NOT NULL DEFAULT 0,
    last_checked TEXT NOT NULL DEFAULT '',
    last_status TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS images (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    bucket_id INTEGER NOT NULL REFERENCES buckets(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    filename TEXT NOT NULL DEFAULT '',
    size INTEGER NOT NULL DEFAULT 0,
    content_type TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_images_bucket ON images(bucket_id, id DESC);
CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS api_keys (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    key_prefix TEXT NOT NULL,
    key_hash TEXT UNIQUE NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_used_at TEXT NOT NULL DEFAULT ''
);
"""

PG_SCHEMA = [
    """CREATE TABLE IF NOT EXISTS buckets (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        label TEXT UNIQUE NOT NULL,
        account_id TEXT NOT NULL DEFAULT '',
        access_key_id TEXT NOT NULL,
        secret_access_key TEXT NOT NULL,
        bucket TEXT NOT NULL,
        endpoint TEXT NOT NULL DEFAULT '',
        public_base_url TEXT NOT NULL DEFAULT '',
        path_style INTEGER NOT NULL DEFAULT 1,
        enabled INTEGER NOT NULL DEFAULT 1,
        failed_count INTEGER NOT NULL DEFAULT 0,
        last_checked TEXT NOT NULL DEFAULT '',
        last_status TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT (now()::text)
    )""",
    """CREATE TABLE IF NOT EXISTS images (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        bucket_id BIGINT NOT NULL REFERENCES buckets(id) ON DELETE CASCADE,
        key TEXT NOT NULL,
        filename TEXT NOT NULL DEFAULT '',
        size BIGINT NOT NULL DEFAULT 0,
        content_type TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL DEFAULT (now()::text)
    )""",
    "CREATE INDEX IF NOT EXISTS idx_images_bucket ON images(bucket_id, id DESC)",
    "CREATE TABLE IF NOT EXISTS meta (k TEXT PRIMARY KEY, v TEXT NOT NULL)",
    """CREATE TABLE IF NOT EXISTS api_keys (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        key_prefix TEXT NOT NULL,
        key_hash TEXT UNIQUE NOT NULL,
        enabled INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT (now()::text),
        last_used_at TEXT NOT NULL DEFAULT ''
    )""",
]


def get_meta(conn, key: str, default: str = "") -> str:
    row = conn.execute("SELECT v FROM meta WHERE k=?", (key,)).fetchone()
    if row is None:
        return default
    return row["v"] if isinstance(row, dict) else row[0]


def set_meta(conn, key: str, value: str):
    conn.execute(
        "INSERT INTO meta(k,v) VALUES(?,?) ON CONFLICT(k) DO UPDATE SET v=excluded.v",
        (key, value),
    )


def init_db():
    if IS_PG:
        import time as _t

        for stmt in PG_SCHEMA:
            for attempt in range(20):
                try:
                    with _pg().connection() as c:
                        c.execute(stmt)
                        c.commit()
                    break
                except Exception as e:
                    if "already exists" in str(e):
                        break
                    _t.sleep(0.5)
        return
    conn = _connect_sqlite()
    try:
        conn.executescript(SQLITE_SCHEMA)
        conn.commit()
        cols = {r[1] for r in conn.execute("PRAGMA table_info(buckets)").fetchall()}
        if "failed_count" not in cols:
            conn.execute("ALTER TABLE buckets ADD COLUMN failed_count INTEGER NOT NULL DEFAULT 0")
        if "last_checked" not in cols:
            conn.execute("ALTER TABLE buckets ADD COLUMN last_checked TEXT NOT NULL DEFAULT ''")
        if "last_status" not in cols:
            conn.execute("ALTER TABLE buckets ADD COLUMN last_status TEXT NOT NULL DEFAULT ''")
        conn.commit()
    finally:
        conn.close()


def insert_returning_id(conn, sql: str, params: tuple) -> int:
    sql = sql.strip().rstrip(";")
    if IS_PG:
        cur = conn.execute(sql + " RETURNING id", params)
        return int(cur.fetchone()["id"])
    cur = conn.execute(sql, params)
    return cur.lastrowid
